+incdir+include
+incdir+tb/memory
../src/util/*.sv
../src/memory/dcache/*.sv
../src/memory/dcache/d0/*.sv
../src/memory/dcache/d1/*.sv
../src/memory/dtlb/*.sv
../src/memory/icache/*.sv
../src/memory/itlb/*.sv
../src/memory/l1_tlb_arbiter/*.sv
../src/memory/l2c_arbiter/*.sv
../src/memory/l2_tlb/*.sv
../src/memory/ptw_tpc/*.sv
../src/memory/*.sv
../src/expipe/branch-unit/*.sv
../src/expipe/cdb/*.sv
../src/expipe/commit-unit/*.sv
../src/expipe/exec-units/*.sv
../src/expipe/issue-unit/*.sv
../src/expipe/load-store-unit/*.sv
../src/expipe/register-file/*.sv
../src/expipe/*.sv
../src/frontend/*.sv
../src/cu/*.sv
../src/*.sv