on:
  pull_request:
    branches:
    - main
jobs:
  lint-format:
    name: Lint and format the code
    runs-on: ghcr.io/vlsi-lab/len5-docker-ci:latest
    steps:
    - uses: actions/checkout@v1
    - name: lint
      run: |
        make lint
    - name: format
      run: |
        make format
